import "./globals.css";
import { Inter } from "next/font/google";
import BodyContent from "./bodyContent";

const inter = Inter({ subsets: ["latin"] });

export const dynamicParams = true,
  revalidate = Infinity,
  fetchCache = "auto",
  runtime = "nodejs",
  preferredRegion = "auto";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <BodyContent children={children} />
      </body>
    </html>
  );
}
